# Generated by Django 4.2.5 on 2023-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_description_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='e_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
